name: Build Webpage
on:
  pull_request:
    branches: [ develop ]

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn run build
