name: Build and Deploy Webpage
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn run build
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        #path: ./webpage
        context: ./webpage
        file: ./webpage/Dockerfile
        tags: pbeke/qownnotes-webpage:latest
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

