name: 'build'

on:
  push:
    branches:
      - develop
    tags-ignore:
      - '*'
  pull_request:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        qt-version: ['5.3', '5.4', '5.13.2', '5.14.2', '5.15.0']
        exclude:
          # xcode not found
          - os: macos-latest
            qt-version: '5.3'
          # xcode not found
          - os: macos-latest
            qt-version: '5.4'
          # win64_mingw73 not found
          - os: windows-latest
            qt-version: '5.3'
          # win64_mingw73 not found
          - os: windows-latest
            qt-version: '5.4'
          # win64_mingw73 not found
          - os: windows-latest
            qt-version: '5.15.0'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # https://github.com/marketplace/actions/install-qt
    - if: contains( matrix.os, 'windows')
      name: Install Qt on Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        arch: win64_mingw73
    - if: false == contains( matrix.os, 'windows')
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
    - name: qmake & make
      run: |
        qmake
        make
